"""empty message

Revision ID: 0bbdccb6f63c
Revises: d7289842a4c8
Create Date: 2025-06-12 15:10:01.210980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bbdccb6f63c'
down_revision: Union[str, None] = 'd7289842a4c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_user', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('custom_user', sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('custom_user', 'modified_at')
    op.drop_column('custom_user', 'created_at')
    # ### end Alembic commands ###
