"""empty message

Revision ID: 33b24b3c0e44
Revises: 2735a6b1181a
Create Date: 2025-06-12 15:31:19.990729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33b24b3c0e44'
down_revision: Union[str, None] = '2735a6b1181a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_user', sa.Column('gender', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('custom_user', 'gender')
    # ### end Alembic commands ###
