"""empty message

Revision ID: 4587b2aabea4
Revises: 9a02a02a345f
Create Date: 2025-06-12 17:35:57.117373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4587b2aabea4'
down_revision: Union[str, None] = '9a02a02a345f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('user_index', 'custom_user', ['mobilenumber', 'email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('user_index', table_name='custom_user')
    # ### end Alembic commands ###
