"""add foreignkey

Revision ID: 5b762d682bbc
Revises: 83dd231e235c
Create Date: 2025-06-16 14:49:36.636690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5b762d682bbc'
down_revision: Union[str, None] = '83dd231e235c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_personal_profile',
    sa.Column('firstname', sa.String(), nullable=True),
    sa.Column('lastname', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('address', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['custom_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_personal_profile_id'), 'user_personal_profile', ['id'], unique=False)
    op.add_column('custom_user', sa.Column('password', sa.String(), nullable=True))
    op.drop_constraint('unique_num_mail', 'custom_user', type_='unique')
    op.create_unique_constraint(None, 'custom_user', ['mobilenumber'])
    op.create_unique_constraint(None, 'custom_user', ['email'])
    op.drop_column('custom_user', 'firstname')
    op.drop_column('custom_user', 'lastname')
    op.drop_column('custom_user', 'gender')
    op.drop_column('custom_user', 'address')
    op.drop_column('custom_user', 'age')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_user', sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('custom_user', sa.Column('address', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('custom_user', sa.Column('gender', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('custom_user', sa.Column('lastname', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('custom_user', sa.Column('firstname', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'custom_user', type_='unique')
    op.drop_constraint(None, 'custom_user', type_='unique')
    op.create_unique_constraint('unique_num_mail', 'custom_user', ['mobilenumber', 'email'], postgresql_nulls_not_distinct=False)
    op.drop_column('custom_user', 'password')
    op.drop_index(op.f('ix_user_personal_profile_id'), table_name='user_personal_profile')
    op.drop_table('user_personal_profile')
    # ### end Alembic commands ###
