"""empty message

Revision ID: 5cb2dbe6e5d7
Revises: cb90dce73ea7
Create Date: 2025-06-13 10:43:26.128108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cb2dbe6e5d7'
down_revision: Union[str, None] = 'cb90dce73ea7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
