"""relationship fields

Revision ID: 798b6cb8b191
Revises: ac5bca5a6c80
Create Date: 2025-06-17 21:15:49.905971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '798b6cb8b191'
down_revision: Union[str, None] = 'ac5bca5a6c80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_mapping',
    sa.Column('role', sa.Integer(), nullable=True),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['role'], ['role_master.id'], ),
    sa.ForeignKeyConstraint(['user'], ['custom_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_mapping_id'), 'role_mapping', ['id'], unique=False)
    op.add_column('role_master', sa.Column('role_name', sa.String(length=15), nullable=True))
    op.drop_constraint('unique_role', 'role_master', type_='unique')
    op.create_unique_constraint('unique_role', 'role_master', ['role_name'])
    op.drop_column('role_master', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role_master', sa.Column('role', sa.VARCHAR(length=15), autoincrement=False, nullable=False))
    op.drop_constraint('unique_role', 'role_master', type_='unique')
    op.create_unique_constraint('unique_role', 'role_master', ['role'], postgresql_nulls_not_distinct=False)
    op.drop_column('role_master', 'role_name')
    op.drop_index(op.f('ix_role_mapping_id'), table_name='role_mapping')
    op.drop_table('role_mapping')
    # ### end Alembic commands ###
