"""Add unique together

Revision ID: 9a02a02a345f
Revises: 33b24b3c0e44
Create Date: 2025-06-12 15:44:14.543872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a02a02a345f'
down_revision: Union[str, None] = '33b24b3c0e44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_num_mail', 'custom_user', ['mobilenumber', 'email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_num_mail', 'custom_user', type_='unique')
    # ### end Alembic commands ###
