"""empty message

Revision ID: c2636d3e98cd
Revises: dd3d7cd67d22
Create Date: 2025-06-18 12:00:00.497413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2636d3e98cd'
down_revision: Union[str, None] = 'dd3d7cd67d22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_mapping', 'role_mapping', ['role', 'user'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_mapping', 'role_mapping', type_='unique')
    # ### end Alembic commands ###
