"""empty message

Revision ID: cb90dce73ea7
Revises: 4587b2aabea4
Create Date: 2025-06-13 10:36:23.348803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb90dce73ea7'
down_revision: Union[str, None] = '4587b2aabea4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('custom_user', 'address',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               existing_nullable=True,
               postgresql_using="address::json")
    op.create_unique_constraint('unique_role', 'role_master', ['role'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_role', 'role_master', type_='unique')
    op.alter_column('custom_user', 'address',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
